### ISSUE TITLE
Configurations for Api Gateway

### ISSUE THREAD

**Issue by rasnesakam** [rika-hq/rika-auth-proto#1]
Proto file needs to apply some options
* `option java_multiple_file = true` this options allows to generate multiple files for each classes in java. It is good if we dont want to generate big files
* `option java_package = "com.rika.services.auth"` this option configures the package name of generated classes Actually, this is up to you. I just offering an opinion about this.

I am referencing [this article](https://protobuf.dev/getting-started/javatutorial/)

**Comment by mkaramuk** [comment]
Thanks Ensar! I think `com.rika.auth` would be better than `com.rika.services.auth`.

**Comment by mkaramuk** [comment]
Completed with fdcf85b
